executable = jobTemplate.sh
#Step=0

should_transfer_files = yes
when_to_transfer_output = ON_EXIT

#use_x509userproxy = true
#Proxy_file = x509up_u104084
Proxy_path = /afs/cern.ch/user/b/bgreenbe/x509up_u104084
transfer_input_files = $(Proxy_path)
#error = err$(Step).Efmrl$(Item)
#output = out$(Step).Efmrl$(Item)
#log = log$(Step).Efmrl$(Item)

error = errfile_$(PROCESS).err
output = outfile_$(PROCESS).out
log = logfile_$(PROCESS).log

request_cpus = 1
request_memory = 2048MB
request_disk = 2048MB

+JobFlavour = "longlunch"

arguments = $(PROCESS) $(Proxy_path)
#queue 10
queue 1
#queue 8
#queue 37
#queue 242
#queue 43
#queue 2
